###  Create User
POST http://localhost:3000/user HTTP/1.1
content-type: application/json

{
    "name": "sample1122",
    "username": "sample1231321",
    "password": "12345678"
}

### Find Role
GET http://localhost:3000/role HTTP/1.1
