###  Create User
POST http://localhost:3001/user HTTP/1.1
content-type: application/json

{
    "name": "sample112",
    "username": "sample123132",
    "password": "12345678"
}

### Find Role
GET http://localhost:3001/role HTTP/1.1
